name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore ./PaymentsLibrary.slnx
      - name: Build
        run: dotnet build ./PaymentsLibrary.slnx --configuration Release --no-restore